require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.telescope")
require("user.gitsigns")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.indentline")
require("user.lsp")
require("user.autosave")
require("user.treesitter-context")
-----------------------------------------------------
-- require("user.autocommands")
-- require("user.impatient")
-- require("user.illuminate")
-- require("user.colorizer")
-- require("user.dap")
-- require("user.copilot")
-- require("user.project")
-- require("user.alpha")
-- vim.g.rustfmt_on_save = 1
